services:
  ipma-api:
    build:
      context: .
      dockerfile: Dockerfile
    # No container_name for scaling support
    # No port mapping - use load balancer or expose specific ports
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - LOG_LEVEL=info
    volumes:
      # Mount logs directory for persistence
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a load balancer (nginx) for scaled instances
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ipma-api
    profiles:
      - scale

volumes:
  dev_node_modules:

networks:
  default:
    name: ipma-network